#!/bin/bash

# Create a Mongo database with administrator user and ro user
# NOTE: password for read only user is given password plus '_ro'
# @version 1.0
# © 2017 Leonardo Ziviani all rights reserved

# MongoDB script
SCRIPT="/tmp/mongo.js"

# Remove old script
rm -f $SCRIPT

# Arguments check
if [ -z "$1" ]; then
	echo "Missing arguments..."
    echo "Use create-mongodb-ts <database> <user> <password>"
	echo "Ex. create-mongodb-ts xxx fake fail"
    exit -1
fi

# Arguments check
if [ -z "$2" ]; then
    echo "Missing arguments..."
    echo "Use create-mongodb-ts <database> <user> <password>"
	echo "Ex. create-mongodb-ts xxx fake fail"
    exit -1
fi

# Arguments check
if [ -z "$3" ]; then
    echo "Missing arguments..."
    echo "Use create-mongodb-ts <database> <user> <password>"
	echo "Ex. create-mongodb-ts xxx fake fail"
    exit -1
fi

clear

# Create script
echo "use $1" > $SCRIPT
echo "db.createUser( { user: '$2', pwd: '$3', roles: [ 'readWrite', 'dbAdmin', 'userAdmin' ] } )" >> $SCRIPT 
echo "db.createUser( { user: '$2_ro', pwd: '$3_ro', roles: [ 'read' ] } )" >> $SCRIPT 
echo "exit"  >> $SCRIPT

# Execute script
mongo -u root -p D0different! --authenticationDatabase admin < $SCRIPT

# Remove old script
rm -f $SCRIPT

# Print results
echo ""
echo "MongoDB database $1 created..."
echo ""
echo "Pass those information to yours developer:"
echo "  Database: $1"
echo "  IP:   db.dodifferent.it (10.10.10.200)"
echo "  Port: 27017"
echo "  FULL access: $2     with password '$3'"
echo "  RO access:   $2_ro  with password '$3_ro'"

exit 0