#!/bin/bash

# Database scripts help
# @ Version 1.2
# © 2017 Leonardo Ziviani all rights reserved

clear

echo ""
echo " Scripts explanation - Database"
echo ""

printf " \033[1mcreate-mongodb-ts\033[0m \t\t - \t Create a MongoDB database with admin and ro user\n"
printf " \033[1mcreate-mysql-ts\033[0m \t\t - \t Create a MySQL database with admin and ro user\n"
printf " \033[1mcreate-oracle-ts\033[0m \t\t - \t Create a standard OracleSQL tablespace\n"
printf " \033[1mcreate-oracle-ts-commander\033[0m \t - \t Create a standard OracleSQL 'commander' tablespace\n"
printf " \033[1mcreate-psql-ts\033[0m \t\t - \t Create a PostgreSQL database with admin and ro user\n"
printf " \033[1mdb-scripts-help-me\033[0m \t\t - \t Database script help\n"
printf " \033[1mdump-mysql\033[0m \t\t\t - \t Dump given MySQL database\n"
printf " \033[1mdump-oracle\033[0m \t\t\t - \t Dump given OracleSQL tablespace\n"
printf " \033[1mdump-oracle-11g\033[0m \t\t - \t Dump given OracleSQL tablespace in compatibility mode for 11g\n"
printf " \033[1mdump-psql\033[0m \t\t\t - \t Dump given PostgreSQL database\n"
printf " \033[1mrestore-mysql\033[0m \t\t\t - \t Restore given MySQL dump\n"
printf " \033[1mrestore-oracle\033[0m \t\t - \t Restore given OracleQL dump\n"
printf " \033[1mrestore-psql\033[0m \t\t\t - \t Restore given PostgreSQL dump\n"

echo ""

exit 0
