#!/bin/bash

# Dump of PostgreSQL db
# @version 1.2
# © 2017 Leonardo Ziviani all rights reserved

# Current date
DATE=$(date +%Y%m%d)
OUT=/tmp

# Arguments check
if [ -z "$1" ]; then
	echo "Missing username..."
	echo "Use dump-psql <user> <database>"
	echo "Ex. dump-psql willy acme"
	exit -1
fi

# Arguments check
if [ -z "$2" ]; then
	echo "Missing database..."
	echo "Use dump-psql <user> <database>"
	echo "Ex. dump-psql willy acme"
	exit -1
fi

# Dump and compress database
pg_dump -U $1 $2 > $OUT/$DATE-$1.dmp
tar -zcvf $OUT/$DATE-$1.tar.gz $OUT/$DATE-$1.dmp
rm -f $OUT/$DATE-$1.dmp

echo "Created file: $OUT/$DATE-$1.tar.gz..."

exit 0