#!/bin/bash

# Fill BLACKLIST chain with blacklist.rules ip list
# @version 1.3
# © 2020 Leonardo Ziviani all rights reserved

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "${RED}This script must be run as root...${DEFAULT}"
	exit -1
fi

# Check if chain "BLACKLIST" exist
CHAIN="$(iptables -n --list BLACKLIST | wc -l)"
if [ "$CHAIN" -lt "3" ]; then
	echo -e "${RED}Missing BLACKLIST chain...${DEFAULT}"
	exit -1
fi

# Flush chain
iptables --flush BLACKLIST

# Fill chain with ips
while read line
do
	iptables -I BLACKLIST -s $line -j DROP
done <  /etc/iptables/blacklist.rules

exit 0
