#!/bin/bash

# Fill BLACKLIST chain with blacklist.rules ip list
# @version 1.3
# © 2020 Leonardo Ziviani all rights reserved

# Flush chain
iptables --flush BLACKLIST

# Fill chain with ips
while read line
do
	iptables -I BLACKLIST -s $line -j DROP
done <  /etc/iptables/blacklist.rules

exit 0
