#!/bin/bash

# Fill BRAZIL chain with brazil.rules ip list
# @version 1.3
# © 2020 Leonardo Ziviani all rights reserved

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "${RED}This script must be run as root...${DEFAULT}"
	exit -1
fi

# Check if chain "BRAZIL" exist
CHAIN="$(iptables -n --list BRAZIL | wc -l)"
if [ "$CHAIN" -lt "3" ]; then
	echo -e "${RED}Missing BLACKLIST chain...${DEFAULT}"
	exit -1
fi

FILE="/etc/iptables/brazil.rules"

# Flush old chain
iptables --flush BRAZIL

# Fill chain with ips
while read line
do
	iptables -I BRAZIL -s $line -j DROP
done < $FILE

exit
