#!/bin/bash

# Fill CHINA chain with china.rules ip list
# @version 1.3
# © 2020 Leonardo Ziviani all rights reserved

FILE="/etc/iptables/china.rules"

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "${RED}This script must be run as root...${DEFAULT}"
	exit -1
fi

# Check if chain "china" exist
CHAIN="$(iptables -n --list china | wc -l)"
if [ "$CHAIN" -lt "3" ]; then
	echo -e "${RED}Missing china chain...${DEFAULT}"
	exit -1
fi

# Flush old chain
iptables --flush CHINA

# Fill chain with ips
while read line
do
	iptables -I CHINA -s $line -j DROP
done < $FILE
