#!/bin/bash

# 'Advanced' iptables firewall rules
# You need iptables (and iptables-persistent on some distro) installed 
# You also need, if you want to use geo-location chain, copy *country*-chain in $BASE folder
# Better to use with 'nohup'
# @version 1.3
# © 2020 Leonardo Ziviani all rights reserved

# Config
SUBNET=( "1.2.3.4/24" "1.1.1.0" "5.6.7.8/22" )		# Trusted IP to allow to remote connect
PORT=( 22 80 443)					# Port to 'forward'

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Files path
BASE="/etc/iptables"
DEBIAN="/etc/iptables/rules.v4"
CENTOS="/etc/iptables/iptables.rules"
ARCH="/etc/iptables/iptables.rules"
RULES="$DEBIAN"

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "$RED This script must be run as root... $DEFAULT"
	exit -1
fi

# Base rules
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Block BAD traffic
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

# Log limit
iptables -N LOGS
iptables -A LOGS -m limit --limit 5/m --limit-burst 10 -j LOG
iptables -A LOGS -j DROP

# Ban chain (manual ip add)
iptables -N BAN
iptables -I INPUT -j BAN
iptables -A BAN -j RETURN

# Blacklist chain (automatic ip update)
iptables -N BLACKLIST
iptables -I INPUT -j BLACKLIST
iptables -A BLACKLIST -j RETURN

# Know bad country chain
iptables -N BRAZIL
iptables -I INPUT -j BRAZIL
iptables -A BRAZIL -j RETURN

iptables -N CHINA
iptables -I INPUT -j CHINA
iptables -A CHINA -j RETURN

iptables -N NIGERIA
iptables -I INPUT -j NIGERIA
iptables -A NIGERIA -j RETURN

iptables -N RUSSIA
iptables -I INPUT -j RUSSIA
iptables -A RUSSIA -j RETURN

iptables -N UKRAINE
iptables -I INPUT -j UKRAINE
iptables -A UKRAINE -j RETURN

# OpenVPN example (change inferface name)
iptables -A INPUT -i tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i eth0 -o tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT

# Loopback
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -s 127.0.0.1 -j ACCEPT

# Allow limited ping request
iptables -A INPUT -p icmp -m limit --limit 10/s --limit-burst 100 -j ACCEPT

# Allow traffic to given port list from everywhere with burst limit
for i in "${PORT[@]}"
do
	iptables -A INPUT -p tcp -m tcp --dport "$i" -m limit --limit 10/s --limit-burst 100 -m state --state NEW,ESTABLISHED -j ACCEPT
done

# Allow traffic from given ip address list
for i in "${SUBNET[@]}"
do
	iptables -A INPUT -s "$1" -j ACCEPT
done

# Allow established connections
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

# Drop unmatched traffic
iptables -A INPUT -j DROP

# Country and blacklist chain automatic update
"$BASE"/update-blacklist
"$BASE"/blacklist-chain
"$BASE"/iptables/brazil-chain
"$BASE"/iptables/china-chain
"$BASE"/iptables/nigeria-chain
"$BASE"/iptables/ukraine-chain
"$BASE"/iptables/russia-chain


# Save rules Debian way
iptables-save > $RULES

exit 0
