#!/bin/bash

# Massive iptables blacklisting of giving address list
# Blacklist file must only contain lines with ip addressese, one per line
# Always perform a backup before proceed!
# @ Version 1.1
# © 2017 Leonardo Ziviani all rights reserved

# Arguments check
if [ -z $1 ]; then
        echo "Missing arguments..."
        echo "Use iptables-custom-blacklist <path-to-list>"
		echo "Ex. iptables-custom-blacklist blacklist.list"
        exit -1
fi

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo "This script must be run as root"
	exit -1
fi

# Check if chain "BAN" exist
CHAIN="$(iptables -n --list BAN | wc -l)"
if [ "$CHAIN" -lt "3" ]; then
	echo "Missing BAN chain..."
	exit -1
fi

# Backup of old rules
rm -f $RULES.bck
cp $RULES $RULES.bck

# Line counter for warning and errors
num=0

# Read file line by line
while read line
do
        # Skip comments
        if [[ "$line" == "#"* ]]; then
            continue
            (num++))
        fi

        words="$(echo $line | wc -w)"

        # Check if line is well formatted (Ex. ipaddress)
        if [ "$words" != "1" ]; then
                echo "$1 contain error at line $num..."
                echo "Uncommented line (use '#' for comments) MUST contain only 1 words and be a valid ip address"
                exit -1
        fi
		ban-ip $l 
        ((num++))
done < $1

exit 0