#!/bin/bash

# Reset iptables to default one
# @ Version 1.0
# © 2018 Leonardo Ziviani all rights reserved

# Iptables configs files
IPV4="/etc/iptables/rules.v4"
IPV6="/etc/iptables/rules.v6"

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "$RED This script must be run as root... $DEFAULT"
	exit -1
fi

# Backup ipv4 rules if exists
if [ -f $IPV4 ]; then
    cp $IPV4 $IPV4.before.erase
fi

# Backup ipv6 rules if exists
if [ -f $IPV6 ]; then
    cp $IPV6 $IPV6.before.erase
fi

# Flush ipv4 rules
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X

# Set default rules
iptables -P INPUT ACCEPT
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Save ipv4 rules
iptables-save > /etc/iptables/rules.v4

# Flush ipv6 rules
ip6tables -F
ip6tables -X
ip6tables -t nat -F
ip6tables -t nat -X
ip6tables -t mangle -F
ip6tables -t mangle -X
ip6tables -t raw -F
ip6tables -t raw -X

# Set default rules
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP

# Save ipv6 rules
ip6tables-save > /etc/iptables/rules.v6

exit 0