#!/bin/bash

# Reset iptables to default one
# © 2020 Leonardo Ziviani all rights reserved

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Iptables configs files
FILE="/etc/iptables/iptables.rules"

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "${RED}This script must be run as root...${DEFAULT}"
	exit -1
fi

# Backup ipv4 rules if exists
if [ -f $FILE ]; then
    cp $FILE $FILE.before.erase
fi

# Flush rules
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X

# Set default rules
iptables -P INPUT ACCEPT
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Save rules
iptables-save > $FILE

exit 0
