#!/bin/bash

# Update blacklist list file
# @version 1.3
# © 2020 Leonardo Ziviani all rights reserved

# File paths
BASE="/etc/iptables/"
LINK="https://myip.ms/files/blacklist/general/latest_blacklist.txt"
OUT="blacklist.rules"

wget $LINK -O $BASE/$OUT
sed -i -e 1,13d $BASE$OUT
sed -i '/:/d' $BASE$OUT
dos2unix --quiet $BASE/$OUT
awk -i inplace '{print $1}' $BASE/$OUT

exit 0
