#---------------------------------------------------------------------
# HAProxy config
#---------------------------------------------------------------------

global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     1000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode		http
    log         global
    option      httplog
    option      dontlognull
    option 		http-server-close
    option 		forwardfor except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 1000
	
# Fronted (where users connect to)
frontend  main *:80
    acl url_static       path_beg       -i /static /images /javascript /stylesheets
    acl url_static       path_end       -i .jpg .gif .png .css .js
    use_backend static          if url_static
    default_backend             app

# Backend (where server redirect) for static content
backend static
    balance     roundrobin
    server      static web1.rtcverona.it:8081 check
    server      static web2.rtcverona.it:8082 check

# Backend (where server redirect) for apps
backend app
    balance     roundrobin
    server      app1 app1.rtcverona.it:8083 check
    server      app2 app2.rtcverona.it:8084 check

