#!/bin/bash

# OpenNMS installer - Debian

cd /tmp
curl -L https://github.com/opennms-forge/opennms-install/archive/1.1.tar.gz | tar xz
cd opennms-install-1.1
bash bootstrap-debian.sh
apt-get install opennms-plugin-provisioning-snmp-hardware-inventory

exit 0