#!/bin/bash

# Restore of OpenNMS database

# DB settings
SUPER_USER=postgres
SUPER_PWD=postgres
USER=opennms
PWD=opennms
DB=opennms

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Check if is running as root
if [ "$EUID" -ne 0 ]; then
	echo -e "$RED This script must be run as root... $DEFAULT"
	exit -1
fi

# Arguments check
if [ -z "$1" ]; then
	echo "Missing dump file, use: restore-db <dump-file>"
	exit -1
fi

# Arguments check
if [ ! -f $1 ]; then
	echo "Dump file not exist..."
	exit -1
fi

# Stop OpenNMS
systemctl stop opennms

# Drop database
su -c 'psql -c "DROP DATABASE $DB;"' -s /bin/bash postgres
su -c 'psql -c "CREATE DATABASE $DB;"' -s /bin/bash postgres

# Restore database
su -c "psql -d $DB -a -f $1" -s /bin/bash postgres

# Start OpenNMS
systemctl start opennms

exit 0