#!/bin/bash

# Disable first login password change for given account
# @ Version 1.0
# © 2017 Leonardo Ziviani all rights reserved

# Arguments check
if [ -z $1 ]; then
	echo "Missing arguments..."
	echo "Use disable-force-password-change <mail>"
	echo "Ex. disable-force-password-change wcoyote@acme.com"
	exit -1
fi

# Zimbra cmd paths
export PATH=$PATH:/opt/zimbra/bin

# Set ldap attributes
zmprov ma $1 zimbraPasswordMustChange FALSE