#!/bin/bash

# Backup given mail accounts
# @version 1.1
# © 2017 Leonardo Ziviani all rights reserved

# Zimbra cmd paths
export PATH=$PATH:/opt/zimbra/bin

# Paths
BACKUP_PATH="/backups"

# Arguments check
if [ -z $1 ]; then
	echo "Missing arguments..."
	echo "Use mailbox-backup <user>"
	echo "Ex. mailbox-backup willycoyote@acme.com"
	exit -1
fi

# Remove old backups if present
rm -f $BACKUP_PATH/$1.tgz

# Perform backups
zmmailbox -z -m $1 getRestURL '/?fmt=tgz' > $BACKUP_PATH/$1.tgz