#!/bin/bash

# Enable password change at first login for every user account
# © 2017 Leonardo Ziviani all rights reserved

# Paths
SCRIPT="/scripts/zimbra"
LIST=/tmp/account.list

# Zimbra cmd paths
export PATH=$PATH:/opt/zimbra/bin

# Get a list of all accounts (except amministrative and daemon ones)
$SCRIPT/list-accounts > $LIST

# Read file line by line
while read line
do
	# Skip comments
	if [[ "$line" == "#"* ]]; then
		continue
		((num++))
	fi

	# Check if file is well formatted
	words="$(echo $line | wc -w)" 
	if [ "$words" != "1" ]; then
		echo "$1 contain error at line $num..."
		echo "Uncommented line (use '#' for comments) MUST contain only 1 words"
		exit -1
	fi
	
	$SCRIPT/enable-force-password-change $line
	echo "$line account password policy successfully edited..."
	((num++))
done < $LIST

rm -f $LIST

exit 0
