#!/bin/bash

# Check the expiration of password and notify the user
# @version 1.4
# © 2017 Leonardo Ziviani all rights reserved

# Arguments check
if [ -z $1 ]; then
	echo "Missing arguments..."
	echo "Use password-expire <mail>"
	echo "Ex. password-expire willy.coyote@acme.com"
	exit -1
fi

# Zimbra cmd paths
export PATH=$PATH:/opt/zimbra/bin

# Valid mail check
if [[ $1 != *"@"* ]]; then
	echo "Wrong username..."
	echo "Use unsername with FQDN (ex. user@domain.it)"
	exit -1
fi

# Mail texts
SUBJECT="Scadenza password"
SUBJECT_EXPIRED="[ERROR] Controllo password"
BODY_PRE="Gentile utente,<br><br>La tua password scadra' fra<b>"
BODY_POST="</b>giorni.<br><br>Per modificarla, collegati al link <a href="https://zimbra.dodifferent.it">Zimbra</a> ed effettua il login.<br>Nella schermata principale, clicca sul tuo username in alto a destra e seleziona 'Cambia Password'.<br>Se non dovesse funzionare, utilizza il link diretto: <a href="https://zimbra.dodifferent.it/h/changepass?skin=harmony">Zimbra Password</a><br><br>Se <b>non</b> utilizzi 'Zimbra Desktop Client', ricordati di aggiornare anche le impostazioni del tuo client mail, o l'account potrebbe bloccarsi.<br><br>Se hai un problema, contatta <a href=\"mailto:sistemi@dodifferent.it?subject=Cambio%20Password\">sistemi@dodifferent.it</a><br><br>La seguente mail e' stata generata automaticamente: si prega di <b>non</b> rispondere.<br><br>Cordialmente,<br>Sistemi Dodifferent"
BODY_EXPIRED_PRE="Gentile Amministratore,<br><br>La password dell'utente <b>"
BODY_EXPIRED_POST="</b>e' scaduta.<br>Cazzialo e procedi al reset prima che si metta ad urlare <b>'Non funziona niente!!!'</b>"

# Retrive password information from Zimbra LDAP
PWD_AGE="$(zmprov ga $1 zimbraPasswordMaxAge | tail -n2 | awk '{print $2}')"
LAST_EDIT="$(zmprov ga $1 zimbraPasswordModifiedTime | tail -n2 | awk '{print $2}' | cut -f1 -d'.')"

# Parse information
YEAR=${LAST_EDIT:0:4}
MONTH=${LAST_EDIT:4:2}
DAY=${LAST_EDIT:6:2}

# Remove first zero of day (ex. 07 will became 7)
if [[ $DAY == 0* ]]; then
        DAY=${DAY:1:1}
fi

# Remove first zero of month (ex. 07 will became 7)
if [[ $MONTH == 0* ]]; then
        MONTH=${MONTH:1:1}
fi

# Calculate how many days remain util password expires
NOW_MONTH="$(date +%m)"
if [[ $NOW_MONTH == 0* ]]; then
        NOW_MONTH=${NOW_MONTH:1:1}
fi

NOW_DAY="$(date +%d)"
if [[ $NOW_DAY == 0* ]]; then
        NOW_DAY=${NOW_DAY:1:1}
fi

let "MAX_DAYS=($YEAR*365 + $MONTH*30 + $DAY + PWD_AGE)"
let "TEN_DAYS=($YEAR*365 + $MONTH*30 + $DAY + PWD_AGE-10)"
let "FIVE_DAYS=($YEAR*365 + $MONTH*30 + $DAY + PWD_AGE-5)"
let "LAST_DAYS=($YEAR*365 + $MONTH*30 + $DAY + PWD_AGE-1)"
let "NOW=($(date +%Y)*365 + $(date +%m)*30 + $(date +%d))"
let "DAY_LEFT=($MAX_DAYS - $NOW)"

if [[ "$DAY_LEFT" == "-"* ]]; then
	echo "Password will never expire..."
elif [ "$DAY_LEFT" -lt "1" ]; then
	#echo "Password will expire in $DAY_LEFT days..."
	echo "$BODY_EXPIRED_PRE $1 $BODY_EXPIRED_POST" | mailx -a 'Content-Type: text/html' -a 'From: password@dodifferent.it' -a 'X-Priority: 1' -a 'X-MSMail-Priority: High' -s "$SUBJECT_EXPIRED" sistemi@dodifferent.it
elif [ "$DAY_LEFT" -lt "11" ]; then
	#echo "Password will expire in $DAY_LEFT days..."
	echo "$BODY_PRE $DAY_LEFT $BODY_POST" | mailx -a 'Content-Type: text/html' -a 'From: password@dodifferent.it' -a 'X-Priority: 1' -a 'X-MSMail-Priority: High' -s "$SUBJECT" "$1"
else
	echo "Password will expire in $DAY_LEFT days... Nothing to do"
fi
