#!/bin/bash

# Send a mail from command line
# Due to Zimbra configuration, 'from' and 'to' address MUST be valid
# @version 1.3
# © 2017 Leonardo Ziviani all rights reserved

# Check for mail package
if ! [ -x "$(command -v mail)" ]; then
	echo "Missing mail package..." >&2
	exit 1
fi

# Arguments check
if [ -z $1 ]; then
        echo "Missing arguments..."
        echo "Use test-mail <from> <to> <subject> <message>"
        echo "Ex. test-mail willie.the.coyote@desert.us support@acme.com 'Dynamite' 'Why your dynamite always explode in my hands?!?'"
		exit -1
fi

# Arguments check
if [ -z $2 ]; then
        echo "Missing arguments..."
        echo "Use test-mail <from> <to> <subject> <message>"
        echo "Ex. test-mail willie.the.coyote@desert.us support@acme.com 'Dynamite' 'Why your dynamite always explode in my hands?!?'"
		exit -1
fi

# Arguments check
if [ -z $3 ]; then
        echo "Missing arguments..."
        echo "Use test-mail <from> <to> <subject> <message>"
        echo "Ex. test-mail willie.the.coyote@desert.us support@acme.com 'Dynamite' 'Why your dynamite always explode in my hands?!?'"
		exit -1
fi

# Arguments check
if [ -z $4 ]; then
        echo "Missing arguments..."
        echo "Use test-mail <from> <to> <subject> <message>"
        echo "Ex. test-mail willie.the.coyote@desert.us support@acme.com 'Dynamite' 'Why your dynamite always explode in my hands?!?'"
		exit -1
fi

echo $4 | /usr/bin/mailx -a "Content-type: text/plain" -a "From: $1" -s $3 $2

exit 0