#!/bin/bash

# Jboss Scripts help
# @ Version 1.2
# © 2017 Leonardo Ziviani all rights reserved

clear

echo ""
echo " Scripts explanation"
echo ""

printf " \033[1mclear-jboss\033[0m \t\t - \t Clear jboss cache ant temp files\033[0m\n"
printf " \033[1mjboss-scripts-help-me\033[0m \t - \t Jboss scripts help\033[0m\n"
printf " \033[1mlog-jboss\033[0m \t\t - \t Run tail on jboss logs\033[0m\n"
echo ""

exit 0