#!/bin/bash

# OpenNMS installer - CentOS

OPENNMS_HOME="/opt/opennms"

# Add OpenNMS stable repo
rpm -Uvh https://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm
rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY

# Update and install needed packages
yum update
yum install opennms
yum install opennms-plugin-provisioning-snmp-hardware-inventory

# Set database
postgresql-setup initdb
systemctl enable postgresql
systemctl start postgresql

sudo -u postgres createuser opennms # sudo -u postgres createuser -P opennms
sudo -u postgres createdb -O opennms opennms
sudo -u postgres psql -c "ALTER USER opennms WITH PASSWORD 'opennms!';"
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'Password1!';"

exit 0