#!/bin/bash

# Dump of OpenNMS database

# Current date
DATE=$(date +%Y%m%d)
OUT=/tools/backup

# DB settings
DB=opennms

# Retention
DAYS=5

# Text color and style
DEFAULT='\e[0m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'

# Check if is running as postgres
if [ "$EUID" -ne 108 ]; then
	echo -e "$RED This script must be run as postgres... $DEFAULT"
	exit -1
fi

# Dump and compress database
pg_dump $DB > $OUT/$DATE-$DB.dmp
tar -zcvf $OUT/$DATE-$DB.tar.gz -C $OUT $DATE-$DB.dmp
rm -f $OUT/$DATE-$DB.dmp

echo "Created file: $OUT/$DATE-$DB.tar.gz..."

# Remove old backups
find "$OUT"* -mtime +"$DAYS" -exec rm {} \;

exit 0