#!/bin/bash

# Disable IPV6 kernel side
# @ Version 1.3
# © 2017 Leonardo Ziviani all rights reserved

# Paths
SYSCTL="/etc/sysctl.conf"
GRUB="/etc/default/grub"

# Config sysctl
echo '' >> $SYSCTL
echo '# Tweaks' >> $SYSCTL
echo 'net.ipv4.tcp_timestamps = 0' >> $SYSCTL
echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> $SYSCTL
echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> $SYSCTL
echo 'net.ipv6.conf.lo.disable_ipv6 = 1' >> $SYSCTL
sysctl -p

# Full disable ipv6
if [ -f $GRUB ]; then
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"\"/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet,ipv6.disable=1\"/g' $GRUB
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\"/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet,ipv6.disable=1\"/g' $GRUB
fi

exit 0