#!/bin/bash

# Setup scripts help
# @ Version 1.2
# © 2017 Leonardo Ziviani all rights reserved

clear

echo ""
echo " Scripts explanation - VM Setup"
echo ""

printf " \033[1mfirst-setup\033[0m \t\t\t - \t First setup of a fresh installed VM\n"
printf " \033[1mnew-host-key\033[0m \t\t\t - \t Generate new RSA key for server identification\n"
printf " \033[1moptimize\033[0m \t\t\t - \t Useful VM optimization (first-setup script will include it)\n"
printf " \033[1mset-elrepo-repository\033[0m \t - \t Set ELRepo repository forn CentOS distro\n"
printf " \033[1mset-hostname\033[0m \t\t\t - \t Set VM hostame (with default dodifferent.it domain)\n"
printf " \033[1mset-static-ip\033[0m \t\t\t - \t Set VM static ip address and configure network interface\n"
printf " \033[1mset-templete-mode\033[0m \t\t - \t Configure VM to became a template\n"
printf " \033[1msetup-scripts-help-me\033[0m \t\t - \t Setup scripts help\n"
echo ""

exit 0