#!/bin/bash

# Pre installation of Oracle Database 12c
# @ Version 1.0
# © 2017 Leonardo Ziviani all rights reserved

# Paths
BASE_PATH="/scripts/installer"
ORACLE_BASHRC"/home/oracle/.bashrc"

# Files
ORACLE_INSTALL_1="linuxamd64_12102_database_1of2.zip"
ORACLE_INSTALL_2="linuxamd64_12102_database_2of2.zip"

# Add user ad groups
groupadd oinstall
groupadd dba
useradd -g oinstall -G dba oracle
passwd oracle

# Set paths
echo "" >> ORACLE_BASHRC
echo "# Oracle" >> ORACLE_BASHRC
echo "export TMPDIR=\$TMP" >> ORACLE_BASHRC
echo "export ORACLE_BASE=/u01/app/oracle" >> ORACLE_BASHRC
echo "export ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome" >> ORACLE_BASHRC
echo "export ORACLE_SID=DEV" >> ORACLE_BASHRC
echo "export PATH=$PATH:$ORACLE_HOME/bin" >> ORACLE_BASHRC
echo "exportLD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib:/usr/lib64" >> ORACLE_BASHRC
echo "exportCLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib" >> ORACLE_BASHRC

# System tuning
echo "" >> /etc/sysctl.conf
echo "# Oracle" >> /etc/sysctl.conf
echo "fs.aio-max-nr = 1048576" >> /etc/sysctl.conf
echo "fs.file-max = 6815744" >> /etc/sysctl.conf
echo "kernel.shmall = 2097152" >> /etc/sysctl.conf
echo "kernel.shmmax = 1987162112" >> /etc/sysctl.conf
echo "kernel.shmmni = 4096" >> /etc/sysctl.conf
echo "kernel.sem = 250 32000 100 128" >> /etc/sysctl.conf
echo "net.ipv4.ip_local_port_range = 9000 65500" >> /etc/sysctl.conf
echo "net.core.rmem_default = 262144" >> /etc/sysctl.conf
echo "net.core.rmem_max = 4194304" >> /etc/sysctl.conf
echo "net.core.wmem_default = 262144" >> /etc/sysctl.conf
echo "net.core.wmem_max = 1048586" >> /etc/sysctl.conf
echo "" >> /etc/security/limits.conf
echo "# Oracle" >> /etc/security/limits.conf
echo "oracle soft nproc 2047" >> /etc/security/limits.conf
echo "oracle hard nproc 16384" >> /etc/security/limits.conf
echo "oracle soft nofile 1024" >> /etc/security/limits.conf
echo "oracle hard nofile 65536" >> /etc/security/limits.conf
sysctl -p
sysctl -a

# Extract installer
mkdir -p /stage
unzip $BASE_PATH/$ORACLE_INSTALL_1 -d /stage/
unzip $BASE_PATH/$ORACLE_INSTALL_2 -d /stage/
chown -R oracle:oinstall /stage/

# Create directory
ln -s /u01 /db
chown -R oracle:oinstall /db
chmod -R 775 /db
chmod g+s /db

# Install stuff
yum install -y binutils.x86_64 compat-libcap1.x86_64 gcc.x86_64 gcc-c++.x86_64 glibc.i686 glibc.x86_64 glibc-devel.i686 glibc-devel.x86_64 ksh compat-libstdc++-33 libaio.i686 libaio.x86_64 libaio-devel.i686 libaio-devel.x86_64 libgcc.i686 libgcc.x86_64 libstdc++.i686 libstdc++.x86_64 libstdc++-devel.i686 libstdc++-devel.x86_64 libXi.i686 libXi.x86_64 libXtst.i686 libXtst.x86_64 make.x86_64 sysstat.x86_64
yum groupinstall -y "X Window System"

# Print helper
echo ""
echo "connect to this server using: ssh -X oracle@oracle.dodifferent.it, then run /stage/database/runInstaller..."
echo ""

exit 0